---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smartpay-ingress
spec:
  rules:
    - host:
      http:
        paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: smartpay-client-service
               port:
                 number: 4201
         - path: /api
           pathType: Prefix
           backend:
             service:
               name: smartpay-server-service
               port:
                 number: 8082
         - path: /socket.io
           pathType: Prefix
           backend:
             service:
               name: smartpay-server-service
               port:
                 number: 8082